name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output_name: cloudslash-linux-amd64
          - goos: linux
            goarch: arm64
            output_name: cloudslash-linux-arm64
          - goos: darwin
            goarch: amd64
            output_name: cloudslash-darwin-amd64
          - goos: darwin
            goarch: arm64
            output_name: cloudslash-darwin-arm64
          - goos: windows
            goarch: amd64
            output_name: cloudslash-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o ${{ matrix.output_name }} cmd/cloudslash/main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.output_name }}
